version: "3.8"
services:
  backend:
    stdin_open: true
    tty: true
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    ports:
      - 8001:8001
    environment:
      - DBServer=mongodb
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=kjemidagen
    volumes:
      - ./database:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
