version: "3.8"
services:
  backend:
    stdin_open: true
    tty: true
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - 8001:80
    environment:
      - DBServer=postgres
  postgres:
    image: postgres:14.1
    restart: always
    environment:
      - POSTGRES_DATABASE=kjemidagen
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=kjemidagen
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5432:5432"
    volumes:
      - ./backend/postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./backend/sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
  pgadmin:
    image: dpage/pgadmin4:6.2
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@kjemidagen.no
      PGADMIN_DEFAULT_PASSWORD: kjemidagen
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - "8081:8080"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - "postgres:pgsql-server"
    depends_on:
      - postgres
volumes:
  db-data:
  pgadmin-data:
