version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:5000
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: mysql:8.0.26
    restart: on-failure
    environment:
      MYSQL_DATABASE: timini
      MYSQL_USER: bucky
      MYSQL_PASSWORD: timini
      MYSQL_ROOT_PASSWORD: timini
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33068:3306
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: on-failure
    ports:
      - 8081:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: timini
    depends_on:
      - db
