version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: frontend.dockerfile
    volumes:
      - ./frontend/static:/app/static:ro
      - ./frontend/src:/app/src:ro
    working_dir: /app/
    ports:
      - 3000:3000
    depends_on:
      - backend
    environment:
      - VITE_SSR_API_URL=http://backend:8000
    command: /bin/sh -c "npm run build; node build/index.js"
  backend:
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    volumes:
      - ./backend/:/app/
    working_dir: /app/
    depends_on:
      - mongodb
    ports:
      - 8000:8000
    environment:
      - DBServer=mongodb
    command: uvicorn kjemidagen.main:app --proxy-headers --host 0.0.0.0 --port 8000
  mongodb:
    image: mongo:5.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=kjemidagen
    volumes:
      - database:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped

volumes:
  database:
  build:
