version: "3.8"
services:
  frontend:
    restart: on-failure
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - 80:3000
      - 24678:24678
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
  backend:
    stdin_open: true
    tty: true
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - 8001:8001
    environment:
      - DBServer=postgres
  postgres:
    image: postgres:14.1
    restart: always
    environment:
      - POSTGRES_DB=kjemidagen
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=kjemidagen
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5432:5432"
    volumes:
      - ./backend/postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./backend/sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
volumes:
  db-data:
  pgadmin-data:
