version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - 80:3000
      - 3000:3000
    depends_on:
      - backend
    environment:
      - VITE_PUBLIC_API_URL=http://backend:8000
  backend:
    stdin_open: true
    tty: true
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    ports:
      - 8000:80
    environment:
      - DBServer=mongodb
    volumes:
      - ./backend/kjemidagen:/kjemidagen
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=kjemidagen
    volumes:
      - ./database:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
