name: Restart frontend

# Controls when the workflow will run
on:
  # Triggers the workflow on push for the "main" branch
  push:
    branches: [ "main" ]
    paths: [ "frontend/**" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Clean: 'false' means we preserve manual file changes, e.g. the .env-files
      - uses: actions/checkout@v3
        with:
          clean: 'false'
          
      - name: Build the frontend with the recent changes
        run: docker compose build frontend
        
      - name: Start the newly built frontend
        run: docker compose up frontend --force-recreate -d
